<?php
/**
 * HiDev plugin for PHPUnit.
 *
 * @link      https://github.com/hiqdev/hidev-phpunit
 * @package   hidev-phpunit
 * @license   BSD-3-Clause
 * @copyright Copyright (c) 2015-2017, HiQDev (http://hiqdev.com/)
 */

namespace hidev\phpunit\tests\unit\console;

use hidev\phpunit\console\PhpunitController;
use hidev\phpunit\console\PhpunitXmlController;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-26 at 10:52:52.
 */
class PhpunitControllerTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var PhpunitController
     */
    protected $object;

    protected function setUp()
    {
        $this->object = new PhpunitController('phpunit', null);
    }

    protected function tearDown()
    {
    }

    /**
     * @todo   Implement testInit().
     */
    public function testInit()
    {
        $this->assertNull($this->object->init());
    }

    public function testGetConfiguration()
    {
        // $this->assertInstanceOf(PhpunitXmlController::class, $this->object->getConfiguration());
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    public function testActionMake()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @todo   Implement testActionRun().
     */
    public function testActionRun()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @todo   Implement testActionGenfake().
     */
    public function testActionGenfake()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @todo   Implement testGenFake().
     */
    public function testGenFake()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @todo   Implement testActionGentest().
     */
    public function testActionGentest()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @todo   Implement testGenSkel().
     */
    public function testGenSkel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @todo   Implement testBuildNamespace().
     */
    public function testBuildNamespace()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @todo   Implement testBuildTestNamespace().
     */
    public function testBuildTestNamespace()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @todo   Implement testBuildClass().
     */
    public function testBuildClass()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @todo   Implement testBuildTestClass().
     */
    public function testBuildTestClass()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @todo   Implement testBuildPath().
     */
    public function testBuildPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @todo   Implement testBuildTestPath().
     */
    public function testBuildTestPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @todo   Implement testBuildFakePath().
     */
    public function testBuildFakePath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
