<?php

/*
 * PHPUnit plugin for HiDev
 *
 * @link      https://github.com/hiqdev/hidev-phpunit
 * @package   hidev-phpunit
 * @license   BSD-3-Clause
 * @copyright Copyright (c) 2015-2016, HiQDev (http://hiqdev.com/)
 */

namespace hidev\phpunit\tests\unit\goals;

use hidev\phpunit\goals\PhpunitXmlGoal;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-26 at 11:03:30.
 */
class PhpunitXmlGoalTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var PhpunitXmlGoal
     */
    protected $object;

    protected function setUp()
    {
        $this->object = new PhpunitXmlGoal('phpunit.xml.dist', null);
    }

    protected function tearDown()
    {
    }

    public function testInit()
    {
        $this->assertSame('xml', $this->object->file->type);
    }
}
